Sprint 2/step 2
Singlelogic/react-burger pull request #4
Opened 2023-09-17 18:26 UTC by Singlelogic

2023-09-17 19:22 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редьюсеры - чистые функции
- Dnd настроен и работает корректно
- Хорошая организация хранилища

Необходимо исправить:

- В консоли есть ошибка связанная с `propTypes`
<img width="471" alt="Снимок экрана 2023-09-17 в 22 13 53" src="https://github.com/Singlelogic/react-burger/assets/60173362/4f81b697-10cd-41c6-9c6e-44fe6bd8a094">

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-17 19:22 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor-item/burger-constructor-item.jsx
> +  const ingredients = useSelector(store => store.burgerConstructor.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-09-17 19:22 UTC, andryxxa93 commented on src/services/burger-ingredients/reducer.js
> +export const burgerIngredientsReducer = (state = initialState, action) => {
**Можно лучше**
Принято один редьюсер помещать в один файл

2023-09-17 19:22 UTC, andryxxa93 commented on src/services/burger-constructor/actions.js
> +        dispatch({
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-09-18 19:04 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-19 10:41 UTC, Singlelogic commented
> Супер, вы отлично поработали! Поздравляю! Работа принята. Желаю удачного продолжения обучения!

Спасибо!

2023-09-19 10:41 UTC, merged